import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ReactNode } from 'react'
import StoreProvider from '../lib/components/StoreProvider/StoreProvider'
import { TPostsResponse } from "@/lib/types";
import { POSTS_URL } from "@/lib/constants";

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const INITIAL_POSTS_URL = POSTS_URL + '&limit=20'

export default async function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  const postsReq = await fetch(INITIAL_POSTS_URL)
  const postsData: TPostsResponse = await postsReq.json()

  return (
    <StoreProvider posts={postsData.posts}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
      </html>
    </StoreProvider>
  )
}
